package:
  name: argdigest
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../   # repo root

build:
  number: 1
  entry_points:
    - argdigest = argdigest.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - versioningit >=3.0.0
  run:
    - python
    - depdigest >=0.9.1
    - numpy >=1.20.0
    - smonitor >=0.13.0

test:
  imports:
    - argdigest

about:
  home: "https://github.com/uibcdf/argdigest"
  license: "MIT"
  summary: "Flexible argument auditing and normalization for scientific libraries."
